name: "Python Install script Poetry Action"
author: "@Tordf"
description: "An action to run https://python-poetry.org/"
branding:
  icon: "truck"
  color: "gray-dark"
inputs:
  poetry-repository:
    description: "The External python repository"
    required: true
  poetry-version:
    description: "The version of poetry to use"
    required: false
    default: "1.2.0"
runs:
  using: "composite"
  steps:
    - run: |
        path="$HOME/.local/"
        echo "$path/bin" >>"$GITHUB_PATH"
        export PATH="$path/bin:$PATH"
        python -m pip install --upgrade pip
        curl -sSL https://install.python-poetry.org | python3 - --version ${{ inputs.poetry-version }}
        poetry self add poetry-artifactregistry-plugin
        poetry config repositories.google ${{ inputs.poetry-repository }}
        poetry config virtualenvs.create false
        poetry install
      shell: bash
