name: "gcloud sdk setup"
author: "@andreavs"
description: "An action to setup gcloud specific to hagal"
branding:
  icon: "truck"
  color: "gray-dark"
inputs:
  gcp_credentials:
    description: "Google cloud service account key"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Cloud SDK
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ inputs.gcp_credentials }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - run: |
        gcloud config set artifacts/repository hagal
        gcloud config set artifacts/location europe-west1
        gcloud auth configure-docker europe-docker.pkg.dev

