name: "balena cli setup"
author: "@andreavs"
description: "An action to setup the balena CLI and login"
branding:
  icon: "truck"
  color: "gray-dark"
inputs:
  api_key:
    description: "Balena API key"
    required: true
  cli_version: 
    description: "Which version of the CLI to use"
    required: false 
    default: "14.3.0"
runs:
  using: "composite"
  steps:
    - run: |
        curl https://github.com/balena-io/balena-cli/releases/download/v${{ inputs.cli_version }}/balena-cli-v${{ inputs.cli_version }}-linux-x64-standalone.zip -L -o balena.zip
        unzip balena.zip
        echo "${PWD}/balena-cli" >> $GITHUB_PATH
      shell: bash
    # needs to be split in two steps so that the PATH is set properly
    - run: | 
        balena login --token ${{ inputs.api_key }}
      shell: bash
