name: Reusable google cloud sdk setup test

on:
  pull_request:
    branches: [ main ]  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2   
    - name: Install dependencies
      uses: 'hagaltech/common-workflows/setup-balena-cli@setup-balena-cli'
      with:
        api_key: ${{ secrets.BALENA_API_KEY }}

    - run: |
        balena orgs