name: Reusable google cloud sdk setup test

on:
  pull_request:
    branches: [ main ]  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2   
    - name: Install dependencies
      uses: 'hagaltech/common-workflows/setup-gcloud-sdk@add-gcloud-action'
      with:
        gcp_credentials: ${{ secrets.GCP_SA_KEY }}
      
    - run: |
        gcloud info
        docker pull europe-docker.pkg.dev/hybrid-316509/hagal/hello-world:latest
